"""
Report formatting and signing shared by all engines.
Engines can set ENGINE_NAME and ENGINE_VERSION on this module.
"""

import json
import hashlib
import datetime
import base64
import os
from typing import List, Dict, Any, Optional

try:
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import padding
    from cryptography.hazmat.backends import default_backend
    CRYPTO_AVAILABLE = True
except ImportError:
    CRYPTO_AVAILABLE = False


ENGINE_NAME = "Lexa Shield Engine"
ENGINE_VERSION = "1.0.0"
HASH_ALGORITHM = "sha256"

SIGNATURE_ENABLED = True
PRIVATE_KEY_PATH = "private_key.pem"

_PRIVATE_KEY = None

LEGAL_DISCLAIMER_EN = (
    "This output is generated by Lexa Shield and is provided solely for informational and internal assessment purposes. "
    "The results reflect similarity, coverage, or consistency indicators derived from text-based analysis and do not constitute legal advice, "
    "regulatory advice, compliance certification, medical advice, financial advice, or professional judgment of any kind. "
    "Lexa Shield does not determine compliance, non-compliance, legality, regulatory status, or certification readiness. "
    "All outputs are intended to support, not replace, human expertise and must be reviewed and validated by qualified professionals "
    "before any decisions, conclusions, or actions are taken. Any reliance on this output without appropriate human review is at the user's "
    "sole discretion and responsibility. Users should consult qualified legal, regulatory, medical, compliance, or other relevant experts "
    "before using this information for any formal, legal, operational, or regulatory purpose."
)

LEGAL_DISCLAIMER_PT = (
    "Este resultado é gerado pela Lexa Shield, um sistema automatizado de análise, e é fornecido exclusivamente para fins informativos "
    "e de avaliação interna. Os resultados refletem indicadores de similaridade, cobertura ou consistência derivados de análise textual "
    "e não constituem assessoria jurídica, regulatória, certificação de conformidade, orientação médica, financeira ou qualquer outro tipo "
    "de parecer profissional. A Lexa Shield não determina conformidade, não conformidade, legalidade, status regulatório ou prontidão para "
    "certificação. Todos os resultados destinam-se a apoiar, e não substituir, a análise de especialistas humanos e devem ser revisados e "
    "validados por profissionais qualificados antes que qualquer decisão, conclusão ou ação seja tomada. Qualquer uso ou dependência deste "
    "resultado sem a devida revisão humana ocorre sob inteira responsabilidade do usuário. Recomenda-se que os usuários consultem profissionais "
    "jurídicos, regulatórios, médicos, de conformidade ou outros especialistas relevantes antes de utilizar estas informações para qualquer "
    "finalidade formal, legal, operacional ou regulatória."
)

IMPORTANT_NOTICE_EN = "Any modification to this output will invalidate the signature"
IMPORTANT_NOTICE_PT = "Qualquer modificação neste resultado invalidará a assinatura"


def _generate_hash(text: str, algorithm: str = "sha256") -> str:
    if algorithm == "sha256":
        return "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest()
    elif algorithm == "md5":
        return "md5:" + hashlib.md5(text.encode("utf-8")).hexdigest()
    raise ValueError(f"Unsupported hash algorithm: {algorithm}")


def normalize_language(lang: str) -> str:
    """Canonical language code: "pt-BR", "en-US" or the trimmed input."""
    if not lang:
        return "en-US"

    normalized = lang.strip().lower()
    if normalized in ("português", "portuguese", "portugues"):
        return "pt-BR"
    if normalized in ("english", "inglês", "ingles"):
        return "en-US"

    if normalized.startswith("pt"):
        return "pt-BR"
    if normalized.startswith("en"):
        return "en-US"

    return lang.strip()


def _get_timestamp_utc() -> str:
    return datetime.datetime.now(datetime.timezone.utc).isoformat().replace("+00:00", "Z")


def _get_legal_disclaimer(language: str = "en-US") -> str:
    if normalize_language(language).lower().startswith("pt"):
        return LEGAL_DISCLAIMER_PT
    return LEGAL_DISCLAIMER_EN


def _get_important_notice(language: str = "en-US") -> str:
    if normalize_language(language).lower().startswith("pt"):
        return IMPORTANT_NOTICE_PT
    return IMPORTANT_NOTICE_EN


def _get_output_language(output_dict: Dict[str, Any]) -> str:
    if not isinstance(output_dict, dict):
        return "en-US"
    lib = output_dict.get("Library")
    if isinstance(lib, dict) and lib.get("Language"):
        return normalize_language(str(lib.get("Language")))
    rm = output_dict.get("Report Metadata")
    if isinstance(rm, dict) and rm.get("Language"):
        return normalize_language(str(rm.get("Language")))
    engine = output_dict.get("Engine")
    if isinstance(engine, dict) and engine.get("Language"):
        return normalize_language(str(engine.get("Language")))
    return "en-US"


def _clean_name(name: str) -> str:
    if not name:
        return "Untitled"
    name_without_ext = os.path.splitext(name)[0]
    return name_without_ext.replace("_", " ").replace("-", " ").title()


def _get_confidence_level(score: float) -> str:
    if score >= 0.90:
        return "very_high"
    elif score >= 0.75:
        return "high"
    elif score >= 0.60:
        return "medium"
    elif score >= 0.40:
        return "low"
    return "very_low"


def _load_private_key(key_path: str = None):
    global _PRIVATE_KEY
    if _PRIVATE_KEY is not None:
        return _PRIVATE_KEY
    if not CRYPTO_AVAILABLE:
        raise ImportError("cryptography library required. Install: pip install cryptography")
    key_path = key_path or PRIVATE_KEY_PATH
    with open(key_path, "rb") as f:
        _PRIVATE_KEY = serialization.load_pem_private_key(
            f.read(), password=None, backend=default_backend()
        )
    return _PRIVATE_KEY


def refresh_output_signature(output_dict: Dict[str, Any]) -> None:
    """Re-sign the output after it changes. Signs it without the Signature key, as format_complete_output does."""
    if not SIGNATURE_ENABLED:
        return
    output_dict.pop("Signature", None)
    sig = _sign_output(output_dict)
    if not sig or str(sig).startswith("SIGNATURE_"):
        return
    display_language = _get_output_language(output_dict)
    output_dict["Signature"] = {
        "Value": sig,
        "Algorithm": "RSA-PSS-SHA256",
        "Key Size": 2048,
        "Note": _get_important_notice(display_language),
    }


def _sign_output(output_dict: Dict[str, Any]) -> str:
    if not CRYPTO_AVAILABLE:
        return "SIGNATURE_UNAVAILABLE_INSTALL_CRYPTOGRAPHY"
    if not SIGNATURE_ENABLED:
        return None
    try:
        private_key = _load_private_key()
        canonical_json = json.dumps(output_dict, sort_keys=True, separators=(",", ":"))
        signature = private_key.sign(
            canonical_json.encode("utf-8"),
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=padding.PSS.MAX_LENGTH
            ),
            hashes.SHA256()
        )
        return base64.b64encode(signature).decode("utf-8")
    except Exception as e:
        import warnings
        warnings.warn(f"Failed to sign output: {e}")
        return f"SIGNATURE_ERROR_{type(e).__name__}"


def extract_compliance_signature_for_task_metadata(results: Any) -> Optional[str]:
    """Session.Hash, stored by the backend as result_metadata['Compliance Signature']."""
    first: Any = None
    if isinstance(results, list) and len(results) > 0:
        first = results[0]
    elif isinstance(results, dict):
        first = results
    if not isinstance(first, dict):
        return None
    sess = first.get("Session")
    if isinstance(sess, dict):
        h = sess.get("Hash")
        if h is not None and str(h).strip() and str(h).strip().upper() != "N/A":
            return str(h).strip()
    return None


def generate_analysis_id(prefix: str = "RPT") -> str:
    """Analysis ID such as RPT-2026-042-COMP."""
    now = datetime.datetime.now(datetime.timezone.utc)
    seq = (now.microsecond // 1000) % 1000
    return f"{prefix}-{now.year}-{seq:03d}-COMP"


def format_report_datetime(timestamp: str = None, timezone_name: str = "UTC", language: str = "en-US") -> str:
    """
    Report date such as "January 28, 2026 @ 4:25 PM UTC". Uses now if timestamp is None.
    No timezone conversion; timezone_name is only the label.
    """
    if timestamp:
        try:
            dt = datetime.datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=datetime.timezone.utc)
        except Exception:
            dt = datetime.datetime.now(datetime.timezone.utc)
    else:
        dt = datetime.datetime.now(datetime.timezone.utc)

    hour_12 = dt.strftime("%I").lstrip("0") or "12"
    month_en = dt.strftime("%B")
    if normalize_language(language).lower().startswith("pt"):
        month_map_pt = {
            "January": "Janeiro",
            "February": "Fevereiro",
            "March": "Março",
            "April": "Abril",
            "May": "Maio",
            "June": "Junho",
            "July": "Julho",
            "August": "Agosto",
            "September": "Setembro",
            "October": "Outubro",
            "November": "Novembro",
            "December": "Dezembro",
        }
        month_display = month_map_pt.get(month_en, month_en)
        return (
            f"{dt.day} de {month_display}, {dt.year} @ "
            f"{hour_12}:{dt.strftime('%M')} {dt.strftime('%p')} {timezone_name}"
        )
    return (
        f"{month_en} {dt.day}, {dt.year} @ "
        f"{hour_12}:{dt.strftime('%M')} {dt.strftime('%p')} {timezone_name}"
    )


def format_single_result(
    term: str,
    score: float,
    threshold: float,
    explanation: str = "",
    suggestion: str = "",
    tags: List[str] = None,
    additional_data: Dict[str, Any] = None,
    **kwargs: Any,
) -> Dict[str, Any]:
    """One detection result. score and threshold are 0-1. additional_data and kwargs are merged in."""
    result = {
        "datetime": _get_timestamp_utc(),
        "term": term,
        "match_percentage": round(score * 100, 2),
        "score": round(score, 4),
        "threshold": round(threshold, 4),
        "passed": score >= threshold,
        "confidence_level": _get_confidence_level(score),
        "explanation": explanation or "Pattern detected in text",
        "suggestion": suggestion or "Review content for compliance",
        "tags": tags or [],
    }
    if additional_data:
        result.update(additional_data)
    if kwargs:
        result.update(kwargs)
    return result


def format_complete_output(
    results: List[Dict[str, Any]],
    input_text: str,
    library_name: str = None,
    metadata: Dict[str, Any] = None,
    document_title: str = None,
    language: str = "en-US",
    engine_name: str = None,
    engine_version: str = None,
    generated_by: str = None,
    generated_at: str = None,
    engine_commit_hash: str = None,
    library_version: str = None,
    library_language: str = None,
    processing_started_at: str = None,
    processing_completed_at: str = None,
    input_source: str = None,
    input_received_at: str = None,
    input_original_filename: str = None,
    input_file_hash: str = None,
    input_file_size: int = None,
) -> Dict[str, Any]:
    """
    Full report dict for an engine.
    input_text is hashed into Session.Hash. language selects the legal disclaimer.
    engine_name / engine_version default to ENGINE_NAME / ENGINE_VERSION.
    Optional sections are added only when their fields are given.
    """
    session_hash = _generate_hash(input_text, HASH_ALGORITHM)
    timestamp = _get_timestamp_utc()

    clean_doc_title = _clean_name(document_title) if document_title else "Untitled Document"
    clean_lib_name = _clean_name(library_name) if library_name else None

    _engine_name = engine_name or ENGINE_NAME
    _engine_version = engine_version or ENGINE_VERSION

    output: Dict[str, Any] = {
        "Engine": {
            "Name": _engine_name,
            "Version": _engine_version,
            "Language": language,
        },
        "Session": {
            "Hash": session_hash,
            "Timestamp UTC": timestamp,
            "Hash Algorithm": HASH_ALGORITHM,
        },
        "Document": {
            "Title": clean_doc_title,
            "Length": len(input_text),
        },
        "Summary": {
            "Total Detections": len(results),
            "Passed Threshold": sum(1 for r in results if r.get("passed", False)),
            "Failed Threshold": sum(1 for r in results if not r.get("passed", False)),
        },
        "Results": results,
        "Legal Disclaimer": _get_legal_disclaimer(language),
    }

    if generated_by or generated_at:
        output["Chain Of Custody"] = {}
        if generated_by:
            output["Chain Of Custody"]["Generated By"] = generated_by
        if generated_at:
            output["Chain Of Custody"]["Generated At"] = generated_at

    if engine_commit_hash or library_version:
        output["Traceability"] = {}
        if engine_commit_hash:
            output["Traceability"]["Engine Commit Hash"] = engine_commit_hash
        if library_version:
            output["Traceability"]["Library Version"] = library_version

    if processing_started_at or processing_completed_at:
        output["Processing"] = {}
        if processing_started_at:
            output["Processing"]["Started At"] = processing_started_at
        if processing_completed_at:
            output["Processing"]["Completed At"] = processing_completed_at
            if processing_started_at:
                try:
                    from dateutil import parser as _dp
                    duration = (
                        _dp.isoparse(processing_completed_at)
                        - _dp.isoparse(processing_started_at)
                    ).total_seconds()
                    output["Processing"]["Duration Seconds"] = round(duration, 3)
                except Exception:
                    pass

    if any([input_source, input_received_at, input_original_filename, input_file_hash, input_file_size]):
        prov: Dict[str, Any] = {}
        if input_source:
            prov["Source"] = input_source
        if input_received_at:
            prov["Received At"] = input_received_at
        if input_original_filename:
            prov["Original Filename"] = input_original_filename
        if input_file_hash:
            prov["File Hash"] = input_file_hash
        if input_file_size is not None:
            prov["File Size"] = input_file_size
        output["Input Provenance"] = prov

    # Library Language is for report display, not the user's text.
    if clean_lib_name:
        lib_info: Dict[str, Any] = {
            "Name": clean_lib_name,
            "Type": "Reference Library",
            "Potential Risk Signals": len(results),
        }
        if library_version:
            lib_info["Version"] = library_version
        if library_language:
            lib_info["Language"] = library_language
        output["Library"] = lib_info

    if metadata:
        output["Metadata"] = {k.replace("_", " ").title(): v for k, v in metadata.items()}

    if SIGNATURE_ENABLED:
        sig = _sign_output(output)
        output["Signature"] = {
            "Value": sig,
            "Algorithm": "RSA-PSS-SHA256",
            "Key Size": 2048,
            "Note": _get_important_notice(language),
        }

    return output
