"""
LexaShield Engine SDK - Output Module
======================================

Shared output formatting and cryptographic signing for ALL compliance engines.
All engines using the SDK import from this module instead of a local output.py.

USAGE IN ENGINES:
-----------------
    from lexashield_engine.output import (
        format_complete_output,
        format_single_result,
        generate_analysis_id,
        format_report_datetime,
        calculate_report_statistics,
    )

SETTING ENGINE NAME (per engine, since each runs in its own process):
----------------------------------------------------------------------
    import lexashield_engine.output as sdk_output
    sdk_output.ENGINE_NAME = "My Engine Name"
    sdk_output.ENGINE_VERSION = "1.2.3"

FUNCTIONS PROVIDED:
-------------------
- format_complete_output()      Main entry point — produces full JSON report dict
- format_single_result()        Format one detection result with standard fields
- generate_analysis_id()        Generate unique report ID (e.g. RPT-2026-001-COMP)
- format_report_datetime()      Format timestamp for display (e.g. January 28, 2026 @ 4:25 PM EST)
- calculate_report_statistics() Compute highest/lowest match, most frequent flag & tag
"""

import json
import hashlib
import datetime
import base64
import os
from typing import List, Dict, Any, Optional

from .pdf_translations import normalize_language

try:
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import padding
    from cryptography.hazmat.backends import default_backend
    CRYPTO_AVAILABLE = True
except ImportError:
    CRYPTO_AVAILABLE = False


# ============================================================
# CONFIGURATION
# ============================================================
# Each engine can override these before calling format_complete_output():
#   import lexashield_engine.output as sdk_output
#   sdk_output.ENGINE_NAME = "My Specific Engine"

ENGINE_NAME = "Lexa Shield Engine"
ENGINE_VERSION = "1.0.0"
HASH_ALGORITHM = "sha256"

SIGNATURE_ENABLED = True
PRIVATE_KEY_PATH = "private_key.pem"
PUBLIC_KEY_PATH = "public_key.pem"

_PRIVATE_KEY = None
_PUBLIC_KEY = None

LEGAL_DISCLAIMER_EN = (
    "This output is generated by Lexa Shield and is provided solely for informational and internal assessment purposes. "
    "The results reflect similarity, coverage, or consistency indicators derived from text-based analysis and do not constitute legal advice, "
    "regulatory advice, compliance certification, medical advice, financial advice, or professional judgment of any kind. "
    "Lexa Shield does not determine compliance, non-compliance, legality, regulatory status, or certification readiness. "
    "All outputs are intended to support, not replace, human expertise and must be reviewed and validated by qualified professionals "
    "before any decisions, conclusions, or actions are taken. Any reliance on this output without appropriate human review is at the user's "
    "sole discretion and responsibility. Users should consult qualified legal, regulatory, medical, compliance, or other relevant experts "
    "before using this information for any formal, legal, operational, or regulatory purpose."
)

LEGAL_DISCLAIMER_PT = (
    "Este resultado é gerado pela Lexa Shield, um sistema automatizado de análise, e é fornecido exclusivamente para fins informativos "
    "e de avaliação interna. Os resultados refletem indicadores de similaridade, cobertura ou consistência derivados de análise textual "
    "e não constituem assessoria jurídica, regulatória, certificação de conformidade, orientação médica, financeira ou qualquer outro tipo "
    "de parecer profissional. A Lexa Shield não determina conformidade, não conformidade, legalidade, status regulatório ou prontidão para "
    "certificação. Todos os resultados destinam-se a apoiar, e não substituir, a análise de especialistas humanos e devem ser revisados e "
    "validados por profissionais qualificados antes que qualquer decisão, conclusão ou ação seja tomada. Qualquer uso ou dependência deste "
    "resultado sem a devida revisão humana ocorre sob inteira responsabilidade do usuário. Recomenda-se que os usuários consultem profissionais "
    "jurídicos, regulatórios, médicos, de conformidade ou outros especialistas relevantes antes de utilizar estas informações para qualquer "
    "finalidade formal, legal, operacional ou regulatória."
)

IMPORTANT_NOTICE_EN = "Any modification to this output will invalidate the signature"
IMPORTANT_NOTICE_PT = "Qualquer modificação neste resultado invalidará a assinatura"


# ============================================================
# INTERNAL HELPERS
# ============================================================

def _generate_hash(text: str, algorithm: str = "sha256") -> str:
    if algorithm == "sha256":
        return "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest()
    elif algorithm == "md5":
        return "md5:" + hashlib.md5(text.encode("utf-8")).hexdigest()
    raise ValueError(f"Unsupported hash algorithm: {algorithm}")


def _get_timestamp_utc() -> str:
    return datetime.datetime.now(datetime.timezone.utc).isoformat().replace("+00:00", "Z")


def _get_legal_disclaimer(language: str = "en-US") -> str:
    if normalize_language(language).lower().startswith("pt"):
        return LEGAL_DISCLAIMER_PT
    return LEGAL_DISCLAIMER_EN


def _get_important_notice(language: str = "en-US") -> str:
    if normalize_language(language).lower().startswith("pt"):
        return IMPORTANT_NOTICE_PT
    return IMPORTANT_NOTICE_EN


def _get_output_language(output_dict: Dict[str, Any]) -> str:
    if not isinstance(output_dict, dict):
        return "en-US"
    lib = output_dict.get("Library")
    if isinstance(lib, dict) and lib.get("Language"):
        return normalize_language(str(lib.get("Language")))
    rm = output_dict.get("Report Metadata")
    if isinstance(rm, dict) and rm.get("Language"):
        return normalize_language(str(rm.get("Language")))
    engine = output_dict.get("Engine")
    if isinstance(engine, dict) and engine.get("Language"):
        return normalize_language(str(engine.get("Language")))
    return "en-US"


def _clean_name(name: str) -> str:
    if not name:
        return "Untitled"
    name_without_ext = os.path.splitext(name)[0]
    return name_without_ext.replace("_", " ").replace("-", " ").title()


def _get_confidence_level(score: float) -> str:
    if score >= 0.90:
        return "very_high"
    elif score >= 0.75:
        return "high"
    elif score >= 0.60:
        return "medium"
    elif score >= 0.40:
        return "low"
    return "very_low"


def _load_private_key(key_path: str = None):
    global _PRIVATE_KEY
    if _PRIVATE_KEY is not None:
        return _PRIVATE_KEY
    if not CRYPTO_AVAILABLE:
        raise ImportError("cryptography library required. Install: pip install cryptography")
    key_path = key_path or PRIVATE_KEY_PATH
    with open(key_path, "rb") as f:
        _PRIVATE_KEY = serialization.load_pem_private_key(
            f.read(), password=None, backend=default_backend()
        )
    return _PRIVATE_KEY


def refresh_output_signature(output_dict: Dict[str, Any]) -> None:
    """
    Recompute the RSA-PSS signature after the output dict was mutated (e.g. platform library metadata).
    Matches the signing step in format_complete_output(): signs the dict without a Signature key, then re-attaches Signature.
    """
    if not SIGNATURE_ENABLED:
        return
    output_dict.pop("Signature", None)
    sig = _sign_output(output_dict)
    if not sig or str(sig).startswith("SIGNATURE_"):
        return
    display_language = _get_output_language(output_dict)
    output_dict["Signature"] = {
        "Value": sig,
        "Algorithm": "RSA-PSS-SHA256",
        "Key Size": 2048,
        "Note": _get_important_notice(display_language),
    }


def _sign_output(output_dict: Dict[str, Any]) -> str:
    if not CRYPTO_AVAILABLE:
        return "SIGNATURE_UNAVAILABLE_INSTALL_CRYPTOGRAPHY"
    if not SIGNATURE_ENABLED:
        return None
    try:
        private_key = _load_private_key()
        canonical_json = json.dumps(output_dict, sort_keys=True, separators=(",", ":"))
        signature = private_key.sign(
            canonical_json.encode("utf-8"),
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=padding.PSS.MAX_LENGTH
            ),
            hashes.SHA256()
        )
        return base64.b64encode(signature).decode("utf-8")
    except Exception as e:
        import warnings
        warnings.warn(f"Failed to sign output: {e}")
        return f"SIGNATURE_ERROR_{type(e).__name__}"


def extract_compliance_signature_for_task_metadata(results: Any) -> Optional[str]:
    """
    Value for ``processing_tasks.result_metadata['Compliance Signature']`` on the backend
    (``Report Metadata`` / ``Session.Hash``).
    """
    first: Any = None
    if isinstance(results, list) and len(results) > 0:
        first = results[0]
    elif isinstance(results, dict):
        first = results
    if not isinstance(first, dict):
        return None
    sess = first.get("Session")
    if isinstance(sess, dict):
        h = sess.get("Hash")
        if h is not None and str(h).strip() and str(h).strip().upper() != "N/A":
            return str(h).strip()
    return None


# ============================================================
# PUBLIC API
# ============================================================

def generate_analysis_id(prefix: str = "RPT") -> str:
    """
    Generate a unique analysis ID (e.g. RPT-2026-042-COMP).

    Args:
        prefix: ID prefix (default: "RPT")

    Returns:
        Analysis ID string
    """
    now = datetime.datetime.now(datetime.timezone.utc)
    seq = (now.microsecond // 1000) % 1000
    return f"{prefix}-{now.year}-{seq:03d}-COMP"


def format_report_datetime(timestamp: str = None, timezone_name: str = "UTC", language: str = "en-US") -> str:
    """
    Format a timestamp for report display in "Report Generated on" style.

    No timezone conversion: displays the time as-is (typically UTC).

    Args:
        timestamp: ISO timestamp string (uses current UTC time if None)
        timezone_name: Label to append, e.g. "UTC" (default: "UTC")
        language: Language code for month rendering (e.g. "en-US", "pt-BR")

    Returns:
        Human-readable string, e.g. "January 28, 2026 @ 4:25 PM UTC"
    """
    if timestamp:
        try:
            dt = datetime.datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=datetime.timezone.utc)
        except Exception:
            dt = datetime.datetime.now(datetime.timezone.utc)
    else:
        dt = datetime.datetime.now(datetime.timezone.utc)

    hour_12 = dt.strftime("%I").lstrip("0") or "12"
    month_en = dt.strftime("%B")
    if normalize_language(language).lower().startswith("pt"):
        month_map_pt = {
            "January": "Janeiro",
            "February": "Fevereiro",
            "March": "Março",
            "April": "Abril",
            "May": "Maio",
            "June": "Junho",
            "July": "Julho",
            "August": "Agosto",
            "September": "Setembro",
            "October": "Outubro",
            "November": "Novembro",
            "December": "Dezembro",
        }
        month_display = month_map_pt.get(month_en, month_en)
        return (
            f"{dt.day} de {month_display}, {dt.year} @ "
            f"{hour_12}:{dt.strftime('%M')} {dt.strftime('%p')} {timezone_name}"
        )
    return (
        f"{month_en} {dt.day}, {dt.year} @ "
        f"{hour_12}:{dt.strftime('%M')} {dt.strftime('%p')} {timezone_name}"
    )


def calculate_report_statistics(results: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Calculate summary statistics across all detection results.

    Returns:
        Dict with highest_match, lowest_match, most_frequent_flag, most_frequent_tag
    """
    if not results:
        return {
            "highest_match": None,
            "lowest_match": None,
            "most_frequent_flag": None,
            "most_frequent_tag": None,
        }

    percentages = [
        r.get("match_percentage", 0)
        for r in results
        if r.get("match_percentage") is not None
    ]

    if percentages:
        hi_r = results[percentages.index(max(percentages))]
        lo_r = results[percentages.index(min(percentages))]
        hi_ref = hi_r.get("article") or hi_r.get("reference") or hi_r.get("term", "N/A")
        lo_ref = lo_r.get("article") or lo_r.get("reference") or lo_r.get("term", "N/A")
        highest_match = f"{max(percentages):.0f}% - {hi_ref}"
        lowest_match = f"{min(percentages):.0f}% - {lo_ref}"
    else:
        highest_match = lowest_match = None

    flag_counts: Dict[str, int] = {}
    for r in results:
        flag = r.get("article") or r.get("reference") or r.get("term")
        if flag:
            flag_counts[flag] = flag_counts.get(flag, 0) + 1

    tag_counts: Dict[str, int] = {}
    for r in results:
        for tag in (r.get("tags") or []):
            tag_counts[tag] = tag_counts.get(tag, 0) + 1

    return {
        "highest_match": highest_match,
        "lowest_match": lowest_match,
        "most_frequent_flag": max(flag_counts, key=flag_counts.get) if flag_counts else None,
        "most_frequent_tag": max(tag_counts, key=tag_counts.get) if tag_counts else None,
    }


def format_single_result(
    term: str,
    score: float,
    threshold: float,
    explanation: str = "",
    suggestion: str = "",
    tags: List[str] = None,
    additional_data: Dict[str, Any] = None,
    **kwargs: Any,
) -> Dict[str, Any]:
    """
    Format a single detection result with standardized fields.

    Args:
        term: Detected term or pattern
        score: Confidence/match score (0.0 to 1.0)
        threshold: Detection threshold
        explanation: Human-readable explanation
        suggestion: Suggested remediation action
        tags: Classification tags
        additional_data: Extra engine-specific fields to merge in
        **kwargs: Any other fields (e.g. reference, article, client_term, observation)
                 are merged into the result for PDF/JSON output.

    Returns:
        Formatted result dictionary
    """
    result = {
        "datetime": _get_timestamp_utc(),
        "term": term,
        "match_percentage": round(score * 100, 2),
        "score": round(score, 4),
        "threshold": round(threshold, 4),
        "passed": score >= threshold,
        "confidence_level": _get_confidence_level(score),
        "explanation": explanation or "Pattern detected in text",
        "suggestion": suggestion or "Review content for compliance",
        "tags": tags or [],
    }
    if additional_data:
        result.update(additional_data)
    if kwargs:
        result.update(kwargs)
    return result


def format_complete_output(
    results: List[Dict[str, Any]],
    input_text: str,
    library_name: str = None,
    metadata: Dict[str, Any] = None,
    document_title: str = None,
    language: str = "en-US",
    # Engine identity (optional overrides for module-level constants)
    engine_name: str = None,
    engine_version: str = None,
    # Auditor / traceability fields (all optional)
    generated_by: str = None,
    generated_at: str = None,
    engine_commit_hash: str = None,
    library_version: str = None,
    library_language: str = None,
    processing_started_at: str = None,
    processing_completed_at: str = None,
    input_source: str = None,
    input_received_at: str = None,
    input_original_filename: str = None,
    input_file_hash: str = None,
    input_file_size: int = None,
) -> Dict[str, Any]:
    """
    Format complete engine output — the main entry point for all engines.

    Args:
        results: List of detection results (each from format_single_result or engine-native)
        input_text: Original analyzed text (used for session hash)
        library_name: Reference library / law pack name
        metadata: Extra key-value pairs to include under "Metadata"
        document_title: Name of the analyzed document
        language: Language code — controls legal disclaimer ("en-US" or "pt-BR")
        engine_name: Override the engine name (defaults to module-level ENGINE_NAME constant)
        engine_version: Override the engine version (defaults to module-level ENGINE_VERSION constant)
        generated_by: User/system that triggered the analysis
        generated_at: Server/host where analysis ran
        engine_commit_hash: Git commit for reproducibility
        library_version: Version of the law pack used
        library_language: Language of the library (e.g. "pt-BR", "en-US"). Used for report display (labels, PDF) when set.
        processing_started_at: ISO timestamp when processing began
        processing_completed_at: ISO timestamp when processing finished
        input_source: How the input arrived (e.g. "client_upload", "API")
        input_received_at: ISO timestamp when input was received
        input_original_filename: Original filename of the uploaded document
        input_file_hash: Hash of the uploaded file
        input_file_size: File size in bytes

    Returns:
        Complete formatted output dictionary ready for JSON export or API response
    """
    session_hash = _generate_hash(input_text, HASH_ALGORITHM)
    timestamp = _get_timestamp_utc()

    clean_doc_title = _clean_name(document_title) if document_title else "Untitled Document"
    clean_lib_name = _clean_name(library_name) if library_name else None

    # Use caller-supplied engine identity if provided, otherwise fall back to module constants
    _engine_name = engine_name or ENGINE_NAME
    _engine_version = engine_version or ENGINE_VERSION

    output: Dict[str, Any] = {
        "Engine": {
            "Name": _engine_name,
            "Version": _engine_version,
            "Language": language,
        },
        "Session": {
            "Hash": session_hash,
            "Timestamp UTC": timestamp,
            "Hash Algorithm": HASH_ALGORITHM,
        },
        "Document": {
            "Title": clean_doc_title,
            "Length": len(input_text),
        },
        "Summary": {
            "Total Detections": len(results),
            "Passed Threshold": sum(1 for r in results if r.get("passed", False)),
            "Failed Threshold": sum(1 for r in results if not r.get("passed", False)),
        },
        "Results": results,
        "Legal Disclaimer": _get_legal_disclaimer(language),
    }

    # Chain of Custody
    if generated_by or generated_at:
        output["Chain Of Custody"] = {}
        if generated_by:
            output["Chain Of Custody"]["Generated By"] = generated_by
        if generated_at:
            output["Chain Of Custody"]["Generated At"] = generated_at

    # Traceability
    if engine_commit_hash or library_version:
        output["Traceability"] = {}
        if engine_commit_hash:
            output["Traceability"]["Engine Commit Hash"] = engine_commit_hash
        if library_version:
            output["Traceability"]["Library Version"] = library_version

    # Processing timestamps
    if processing_started_at or processing_completed_at:
        output["Processing"] = {}
        if processing_started_at:
            output["Processing"]["Started At"] = processing_started_at
        if processing_completed_at:
            output["Processing"]["Completed At"] = processing_completed_at
            if processing_started_at:
                try:
                    from dateutil import parser as _dp
                    duration = (
                        _dp.isoparse(processing_completed_at)
                        - _dp.isoparse(processing_started_at)
                    ).total_seconds()
                    output["Processing"]["Duration Seconds"] = round(duration, 3)
                except Exception:
                    pass

    # Input provenance
    if any([input_source, input_received_at, input_original_filename, input_file_hash, input_file_size]):
        prov: Dict[str, Any] = {}
        if input_source:
            prov["Source"] = input_source
        if input_received_at:
            prov["Received At"] = input_received_at
        if input_original_filename:
            prov["Original Filename"] = input_original_filename
        if input_file_hash:
            prov["File Hash"] = input_file_hash
        if input_file_size is not None:
            prov["File Size"] = input_file_size
        output["Input Provenance"] = prov

    # Library section (include Language when provided — used for report display, not user text)
    if clean_lib_name:
        lib_info: Dict[str, Any] = {
            "Name": clean_lib_name,
            "Type": "Reference Library",
            "Potential Risk Signals": len(results),
        }
        if library_version:
            lib_info["Version"] = library_version
        if library_language:
            lib_info["Language"] = library_language
        output["Library"] = lib_info

    # Extra metadata
    if metadata:
        output["Metadata"] = {k.replace("_", " ").title(): v for k, v in metadata.items()}

    # Cryptographic signature
    if SIGNATURE_ENABLED:
        sig = _sign_output(output)
        output["Signature"] = {
            "Value": sig,
            "Algorithm": "RSA-PSS-SHA256",
            "Key Size": 2048,
            "Note": _get_important_notice(language),
        }

    return output
